export const contactsList = [
    {
      id: 1,
      firstName: 'Rajeev',
      lastName: 'Sharma',
      dob: '1986-02-12',
      email: 'rajeevsharma@example.com',
      phone: '2528763211',
      address: '1001 noble st, ste 1',
      city: 'Fairbanks',
      state: 'AK',
      zip: '99701',
    },
    {
      id: 2,
      firstName: 'Eesha',
      lastName: 'Sharma',
      dob: '1995-07-04',
      email: 'eeshasharma@example.com',
      phone: '9876543210',
      address: '456 Elm St',
      city: 'Anchorage',
      state: 'AK',
      zip: '99508',
    },
    {
      id: 3,
      firstName: 'Jane',
      lastName: 'Smith',
      dob: '2024-03-15',
      email: 'jane.smith@example.com',
      phone: '9876543210',
      address: '456 Elm St',
      city: 'Shelbyville',
      state: 'IL',
      zip: '62565',
    },
  ];